### ISSUE TITLE
Autoscroll the project files panel when you select a file in the editor

### ISSUE THREAD

**Issue by stcarrez** [AdaCore/gps#18]
This is en enhancement suggestion.

On large projects, when you have many files opened and you switch from one file to another
in the editor main window, the left project files panel that displays the list of files does not automatically
scroll to show the new file location.

The Intellij Idea has the "Autoscroll to source" and "Autoscroll from source" options that allows
to synchronize the project files panel with the editor panel. These are two settings that can be
enabled or not depending on the user preference.

These two features are really helpful in large projects because you can quickly jump to the file.

The double click on the project files is just a real pain.

**Comment by briot** [comment]
(former GPS developer, no longer involved) I like this idea. The reason it was not implemented initially is for efficiency reasons. The contents of the Project view was populated lazily, and thus we did not have all the files information in there. A further complication is that a given source file might occur several times (if you use an aggregate project, or configure the Project view to nest imported projects), so there could be ambiguities as to which one GPS should select.

But since we implemented the filtering at the top of the Project view, it would now be much easier to implement your suggestion. One possible approach, which could be done from a pure python plugin, is simply to populate the filter, though that is definitely not the best.

Do you know about the "Locate in Project view" contextual menu in editors ? That might help too.

Finally, I think you will need to provide more context for your last sentence, which seems unrelated to the rest of your suggestions ?

Personal note: nice to hear from you again ! :-)

**Comment by stcarrez** [comment]
To open a file in the editor, you can double click on the file in the project files tree. This double click is
a pain.  To solve that, Intellij Idea has the "Autoscroll to source" which when enabled, allows you to
use the simple click (which does nothing today in gps). I guess this mode could be easily implemented.

Thanks for the "Locate in Project view" this helps a little but it would really help more to have it run
automatically when you click on the editor tab. I really love Intellij Idea for that (and other things)!

**Comment by setton** [comment]
I think a python plugin could easily run "Locate in Project View" automatically...

**Comment by AnthonyLeonardoGracio** [comment]
Hi Stephane,

You can now enable the "Auto Locate File" plugin via the Preferences/Plugins page to have this feature.

Regards,
