### ISSUE TITLE
Can't load project with scenario variables with no default

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#73]
If I declare a scenario variable like

~~~~ lang-ada
type Platform_Type is ("UNIX", "Windows");
Platform : Platform_Type := external("Platform); --Notice no default
~~~~

so that the parameter is required to be specified on the call to gprbuild, because no sensible default exists.

It works fine with gprbuild.

GPS however breaks down and wont load the project.

**Comment by Entomy** [comment]
Oh oops, this is with the new 20190106 build

**Comment by briot** [comment]
Did you pass a `-XPlatform=UNIX` command line argument ? Otherwise, GPS has no value for that scenario variable, and, just like gprbuild, will complain.

**Comment by Entomy** [comment]
So I have to call GPS from the command line to set the variable that GPS has a GUI for setting?

**Comment by briot** [comment]
I haven't followed GPS development in the last two years (I used to be a developer), so take this with a grain of salt.
At some point, GPS was just choosing the first possible value as a default, so you did not have to provide a value. Then from the Scenario view you could set a value, which was reused as the default the next time you started GPS. So maybe there was a recent change here (or an unintentional regressions).
I was providing the `-X` as a workaround for now, so that you do not have to change your project file.

**Comment by Entomy** [comment]
Okay, so GPS _was_ doing the sensible thing historically and regressed.

Sorry, I thought you were telling me this was a won't-fix because there was a way of doing it already. I've been told that quite a few times by AdaCore employees and have come to expect it. Thank you for not doing so.

**Comment by fedor-rybin** [comment]
GPS is following gprbuild here. If there is no default specified the user must specify it by hand.
While loading the project with no default specified for external you'll get a bunch of messages in "Messages" tab:

/path/to/simple.gpr:4:29: undefined external reference "Platform"
Some externals are undefined, project may be loaded incompletely
Set values of corresponding externals and reload the project

So you need to go to "Scenario" tab and select the value you want, then apply it. The project will be recomputed and properly loaded. You might need to change the selected value once to make "apply" button cleckable.

**Comment by ogorodnik** [comment]
Right now we don't have a plan to change this behavior.
But thank you for the report.
