### ISSUE TITLE
Missing autocomplete suggestions

### ISSUE THREAD

**Issue by ProudPenguin** [AdaCore/gps#87]
I am using `GPS 19.1 (20190106) hosted on x86_64-pc-linux-gnu` on Ubuntu 18.04.2 LTS with `GNAT Community 2019 (20190517-83)` and created the following short example Ada source code:

```ada
with Ada.Containers.Vectors;
with Ada.Text_IO;

procedure Main is
   type Record_Type is record
      A : Natural;
      B : Integer;
   end record;

   package Records_Vector is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Record_Type);

   My_Records : Records_Vector.Vector;
begin
   My_Records.Append ((A => 1, B => 2));
   My_Records.Append ((A => 2, B => 4));

   for Record_Entry of My_Records loop
      Ada.Text_IO.Put_Line (Natural'Image (Record_Entry.A));
      Ada.Text_IO.Put_Line (Integer'Image (Record_Entry.B));
   end loop;
end Main;
```

When typing `Ada.Text_IO.Put_Line (Natural'Image (Record_Entry.` no autocomplete suggestions are provided for the record type `Record_Type`.

**Comment by ogorodnik** [comment]
It is expected because for this version of GPS autocompletion works for compiled files. It means that Record_Type should be compiled before to include it in the Xref database.

Right now we are switching to new technology based on LibAdaLang which allows doing autocompletion and other things without necessity source files been compiled.

Thank you for the report.
